VOLUME_MIN_FIABLE = 1000
JOURS_MIN_FIABLE = 10

SEUIL_TENDANCE = 0.10
NB_JOURS_COMPARAISON = 5

SEUIL_TAUX_CRITIQUE = 0.50
SEUIL_TAUX_VIGILANCE = 0.70
SEUIL_HAUSSE = 20.0
SEUIL_BAISSE = -30.0
SEUIL_CAUSE_DOMINANTE = 0.60
CONTAMINATION_ISOLATION_FOREST = 0.15

SEUIL_ALERTE_CA_PCT = 27.7

SEUIL_TENTATIVES_REESSAI = 2
SEUIL_TENTATIVES_BLOQUE = 3
