input {
  file {
    path => "/usr/share/logstash/data-logs/orange/*.cdr"
    start_position => "beginning"
  }
}
filter {
  csv {
    separator => ";"
    columns => ["timestamp", "service_class", "subscriber", "offer", "price", "result_code", "msg", "short_code", "parameters"]
    skip_empty_columns => false
  }
  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }
  mutate {
    convert => {
      "price" => "float"
      "result_code" => "integer"
    }
  }
  if [msg] == "Suivi conso" {
    mutate {
      add_field => { "event_type" => "consultation" }
    }
  } else if [msg] == "success" {
    mutate {
      add_field => { "event_type" => "transaction_success" }
    }
  } else if [msg] {
    mutate {
      add_field => { "event_type" => "transaction_failed" }
    }
  } else {
    mutate {
      add_field => { "event_type" => "unknown" }
    }
  }
  translate {
    field => "offer"
    destination => "offer_name"
    dictionary_path => "/usr/share/logstash/dictionaries/offers_catalogue.yml"
    fallback => "%{offer}"
  }
  if [event_type] == "transaction_failed" {
    if [result_code] and [result_code] != "" {
      translate {
        field => "result_code"
        destination => "error_description"
        dictionary_path => "/usr/share/logstash/dictionaries/error_codes.yml"
        fallback => "Code non documente (%{result_code})"
      }
    } else {
      mutate {
        add_field => { "error_description" => "%{msg}" }
      }
    }
  }
}output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ussd-cdr-logs"
  }
  stdout { codec => rubydebug }
}
